generic-ner-ui/generic-ner-ui/generic_ner_ui/urls.py
import tempfile
from decorator_include import decorator_include
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.http import JsonResponse
from django.urls import include, path, re_path

from generic_ner_ui import settings
from generic_ner_ui.utils import redirect

import datetime
import itertools
import json
from pathlib import Path
from generic_ner_ui.models import Run
from django.db.models import Q
from django.http import HttpResponse
from main.views import create_single_pdf, download_pdf
from generic_ner_ui.settings import SECRET, ALLOWED_IPS
from loguru import logger
from main.processing import compress
from main.processing import download_minio_file

def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[-1].strip()
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def validate_access(request):
    try:
        #if get_client_ip(request) not in ALLOWED_IPS:
        #    return False
        request_secret = request.GET.getlist("secret")[0]
        if request_secret != SECRET:
            return False
        return True
    except Exception as e:
        logger.info(f"{get_client_ip(request)}, {e}")
        return False


def search_files(request):
    try:
        if not validate_access(request):
            return JsonResponse([{"access": "denied"}], safe=False)
        request_date = request.GET.getlist("lastApproved")[0]
        date = datetime.datetime.strptime(request_date, "%Y%m%dT%H%M%S%z").strftime("%Y-%m-%d %H:%M:%S.%f%z")
    except Exception as e:
        return JsonResponse([{"exception": str(e)}], safe=False)

    runs = Run.objects.filter( (Q(latest_review_date__gt=date) | Q(finish_date__gt=date)) & Q(marked_complete=True) )
    runs = list(reversed(runs))

    context = []
    for r in runs:
        if r.latest_review_date:
            date = r.latest_review_date.strftime("%Y%m%dT%H%M%S%z")
        elif r.finish_date:
            date = r.finish_date.strftime("%Y%m%dT%H%M%S%z")
        else:
            date = ""
        context.append({
            "id": r.task_id,
            "lastApproved": date,
            "title": f"{Path(r.file_name).stem}.pdf",
            "resultPdfUrl": request.build_absolute_uri(f"/bow/{r.task_id}/result.pdf?secret={SECRET}").replace("http://", "https://"),
            "jsonUrl": request.build_absolute_uri(f"/bow/{r.task_id}/result.json?secret={SECRET}").replace("http://", "https://")
        })
    return JsonResponse(context, safe=False, json_dumps_params={'ensure_ascii': False})


def download_json(request, id):
    if not validate_access(request):
        return JsonResponse([{"access": "denied"}], safe=False)

    run = Run.objects.get(task_id=id)
    data = run.result_data.data

    file_root = Path(run.file_name).stem
    filename_base = Path(data['output']).stem

    date = run.upload_date.strftime('%Y-%m-%d_%H-%M-%S')
    if run.latest_review_date:
        date = run.latest_review_date.strftime('%Y-%m-%d_%H-%M-%S')
    elif run.finish_date:
        date = run.finish_date.strftime('%Y-%m-%d_%H-%M-%S')
    filename_json = f"{filename_base}_AC-OCR-BOW_{date}.json"
    request_json_path = f"{file_root}/{filename_json}"

    response = HttpResponse(json.dumps(data, ensure_ascii=False), content_type='application/json')
    response['Content-Disposition'] = f'attachment; filename="{request_json_path}"'
    return response


def download_pdf(request, id):
    if not validate_access(request):
        return JsonResponse([{"access": "denied"}], safe=False)

    run = Run.objects.get(task_id=id)

    # PDF un-reviewed
    if not run.latest_review_date:
        ext = f"_AC-OCR-BOW-Unrev_{str(run.upload_date.strftime('%Y-%m-%d_%H-%M-%S'))}.pdf"
        pdf_path = f"{Path(run.file_name).stem}{ext}"

        minio_path = run.result_prep["output"]
        response = download_minio_file(minio_path, content_type="application/pdf")
        response['Content-Disposition'] = f'attachment; filename="{pdf_path}"'
        return response

    ext = f"_AC-OCR-BOW-Unrev_{str(run.upload_date.strftime('%Y-%m-%d_%H-%M-%S'))}.pdf"
    if run.finish_date != None:
        ext = f"_AC-OCR-BOW-Unrev_{str(run.finish_date.strftime('%Y-%m-%d_%H-%M-%S'))}.pdf"
    if run.latest_review_date != None:
        ext = f"_AC-OCR-BOW-Rev_{str(run.latest_review_date.strftime('%Y-%m-%d_%H-%M-%S'))}.pdf"

    pdf_path = f"{Path(run.file_name).stem}{ext}"

    with tempfile.NamedTemporaryFile(suffix='.pdf', delete=True) as temp_1:
        _ = create_single_pdf(run.result_data.data['pages'], temp_1.name)

        with tempfile.NamedTemporaryFile(suffix='.pdf', delete=True) as temp_2:
            success = compress(temp_1.name, temp_2.name, power=1)
            export_file = temp_1.name
            if success:
                export_file = temp_2.name

            with open(export_file, 'rb') as file:
                response = HttpResponse(file.read(), content_type='application/pdf')
                response['Content-Disposition'] = f'attachment; filename="{pdf_path}"'
                return response

    #response = HttpResponse(content_type='application/pdf')
    #response['Content-Disposition'] = f'attachment; filename="{pdf_path}"'
    #response = create_single_pdf(run.result_data.data['pages'], response)
    #return response


def health_check(request):
    return JsonResponse({"status": "up"})


urlpatterns = [
    re_path(r'^$', lambda _: redirect('/main')),
    path('', include('social_django.urls', namespace='social')),
    path('admin/', admin.site.urls),
    path('main/', decorator_include(login_required, ('main.urls', "main"),
                                    namespace="main")),
    path('health', health_check),
    path('search', search_files),
    path('<str:id>/result.pdf', download_pdf),
    path("<str:id>/result.json", download_json),
    url(r'^logout/$', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
]

generic-ner-ui/generic-ner-ui/main/urls.py
from django.urls import path

from . import views

"""Register urls here
"""

urlpatterns = [
    path("", views.base_page, name="base"),
    path("upload", views.upload, name="upload"),
    path("admin", views.admin_page, name="admin"),
    path("view/<str:id>", views.details, name="details"),
    path("delete_paths", views.delete_files, name="delete_files"),
    path("delete_tiffs", views.delete_tiffs, name="delete_tiffs"),
    path("rename_group", views.rename_group, name="rename_group"),
    path("delete/<str:id>", views.delete, name="delete"),
    path("view/<str:id>/<str:view>", views.details, name="details"),
    path("img/<str:id>/<int:page>.png", views.image, name="image"),
    path("ocr_data.zip", views.download_all, name="download_data"),
    path("<str:id>/result.pdf", views.download_pdf, name="download_pdf"),
    path("<str:id>/result.txt", views.download_txt, name="download_txt"),
    path("<str:id>/result.json", views.download_json, name="download_json"),
    path("<str:id>/original", views.download_original, name="download_original"),
    path("uploads", views.upload_view, name="upload_view"),
    path("updates", views.check_status_updates, name="check_status_updates"),
    path("corrections", views.update_human_corrections, name="update_human_corrections"),
    path("update_marked_complete", views.update_marked_complete, name="update_marked_complete"),
]

generic-ner-ui/generic-ner-ui/templates/global/back.html
{% load icons %}
<a id="back-button" href="{% url 'main:base' %}" style="cursor: pointer;border-bottom: 2px solid #539ed9;padding: 5px;text-decoration: none!important;color: #075071!important;margin-top: 20px;margin-bottom: 30px;display: inline-block;">
    {% icon 'back' extra_classes='back-icon' %} <span style="top: -2px;position: relative;">Go Back to All</span>
</a>

generic-ner-ui/generic-ner-ui/templates/global/header.html
{% load icons %}
{% load save_static %}
<nav class="navbar navbar-default fixed-top">
    <div class="container">
        <div class="navbar-header">
            <img src="{% save_static 'img/tu_schwarz.gif' %}" class="icon">
            <h1 class="navbar-brand">BOW</h1>
            <h4 class="navbar-brand2">Batch OCR Webservice</h4>
        </div>
        <div>      
        {% if upload %}
        {% include "global/upload.html" %}
        {% endif %}
        <span class="user-name">Hello {{ request.user }} <a href="{{ logout_url}}{% filter urlencode %}{{ request.scheme }}://{{ request.get_host }}{% url 'logout' %}{% endfilter %}">(Logout)</a></span>
        </div>
        <script type="application/javascript">
            $(function () {
                $('[data-toggle="tooltip"]').tooltip({"html":true})
            });
        </script>
    </div>
</nav>

generic-ner-ui/generic-ner-ui/templates/global/select-button.html
{% load icons %}

<button class="btn btn-primary{% if selector == view %} active{% endif %}" data-toggle="tooltip" data-placement="top" title="{{ title }}"
        onclick="location.href='{{ url }}';">{% if icon_name %}{% icon icon_name %}{% else %}{{ title }}{% endif %}
</button>

generic-ner-ui/generic-ner-ui/templates/global/tooltip.html
<p>Entity-Type: <b>{{ entity.type}}</b><br>
Entity-Value: {{ entity.value }}</p>

generic-ner-ui/generic-ner-ui/templates/global/upload.html
{% load icons %}
<a class="btn btn-primary" href="{% url 'main:upload_view' %}" style="color:white; background: #075071;margin-left:20px">
    {% icon 'upload' %} Upload New Files
</a>