generic-ner-ui/generic-ner-ui/generic_ner_ui/urls.py
import tempfile
from decorator_include import decorator_include
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.http import JsonResponse
from django.urls import include, path, re_path

from generic_ner_ui import settings
from generic_ner_ui.utils import redirect

import datetime
import itertools
import json
from pathlib import Path
from generic_ner_ui.models import Run
from django.db.models import Q
from django.http import HttpResponse
from main.views import create_single_pdf, download_pdf
from generic_ner_ui.settings import SECRET, ALLOWED_IPS
from loguru import logger
from main.processing import compress
from main.processing import download_minio_file

def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[-1].strip()
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def validate_access(request):
    try:
        #if get_client_ip(request) not in ALLOWED_IPS:
        #    return False
        request_secret = request.GET.getlist("secret")[0]
        if request_secret != SECRET:
            return False
        return True
    except Exception as e:
        logger.info(f"{get_client_ip(request)}, {e}")
        return False


def search_files(request):
    try:
        if not validate_access(request):
            return JsonResponse([{"access": "denied"}], safe=False)
        request_date = request.GET.getlist("lastApproved")[0]
        date = datetime.datetime.strptime(request_date, "%Y%m%dT%H%M%S%z").strftime("%Y-%m-%d %H:%M:%S.%f%z")
    except Exception as e:
        return JsonResponse([{"exception": str(e)}], safe=False)

    runs = Run.objects.filter( (Q(latest_review_date__gt=date) | Q(finish_date__gt=date)) & Q(marked_complete=True) )
    runs = list(reversed(runs))

    context = []
    for r in runs:
        if r.latest_review_date:
            date = r.latest_review_date.strftime("%Y%m%dT%H%M%S%z")
        elif r.finish_date:
            date = r.finish_date.strftime("%Y%m%dT%H%M%S%z")
        else:
            date = ""
        context.append({
            "id": r.task_id,
            "lastApproved": date,
            "title": f"{Path(r.file_name).stem}.pdf",
            "resultPdfUrl": request.build_absolute_uri(f"/bow/{r.task_id}/result.pdf?secret={SECRET}").replace("http://", "https://"),
            "jsonUrl": request.build_absolute_uri(f"/bow/{r.task_id}/result.json?secret={SECRET}").replace("http://", "https://")
        })
    return JsonResponse(context, safe=False, json_dumps_params={'ensure_ascii': False})


def download_json(request, id):
    if not validate_access(request):
        return JsonResponse([{"access": "denied"}], safe=False)

    run = Run.objects.get(task_id=id)
    data = run.result_data.data

    file_root = Path(run.file_name).stem
    filename_base = Path(data['output']).stem

    date = run.upload_date.strftime('%Y-%m-%d_%H-%M-%S')
    if run.latest_review_date:
        date = run.latest_review_date.strftime('%Y-%m-%d_%H-%M-%S')
    elif run.finish_date:
        date = run.finish_date.strftime('%Y-%m-%d_%H-%M-%S')
    filename_json = f"{filename_base}_AC-OCR-BOW_{date}.json"
    request_json_path = f"{file_root}/{filename_json}"

    response = HttpResponse(json.dumps(data, ensure_ascii=False), content_type='application/json')
    response['Content-Disposition'] = f'attachment; filename="{request_json_path}"'
    return response


def download_pdf(request, id):
    if not validate_access(request):
        return JsonResponse([{"access": "denied"}], safe=False)

    run = Run.objects.get(task_id=id)

    # PDF un-reviewed
    if not run.latest_review_date:
        ext = f"_AC-OCR-BOW-Unrev_{str(run.upload_date.strftime('%Y-%m-%d_%H-%M-%S'))}.pdf"
        pdf_path = f"{Path(run.file_name).stem}{ext}"

        minio_path = run.result_prep["output"]
        response = download_minio_file(minio_path, content_type="application/pdf")
        response['Content-Disposition'] = f'attachment; filename="{pdf_path}"'
        return response

    ext = f"_AC-OCR-BOW-Unrev_{str(run.upload_date.strftime('%Y-%m-%d_%H-%M-%S'))}.pdf"
    if run.finish_date != None:
        ext = f"_AC-OCR-BOW-Unrev_{str(run.finish_date.strftime('%Y-%m-%d_%H-%M-%S'))}.pdf"
    if run.latest_review_date != None:
        ext = f"_AC-OCR-BOW-Rev_{str(run.latest_review_date.strftime('%Y-%m-%d_%H-%M-%S'))}.pdf"

    pdf_path = f"{Path(run.file_name).stem}{ext}"

    with tempfile.NamedTemporaryFile(suffix='.pdf', delete=True) as temp_1:
        _ = create_single_pdf(run.result_data.data['pages'], temp_1.name)

        with tempfile.NamedTemporaryFile(suffix='.pdf', delete=True) as temp_2:
            success = compress(temp_1.name, temp_2.name, power=1)
            export_file = temp_1.name
            if success:
                export_file = temp_2.name

            with open(export_file, 'rb') as file:
                response = HttpResponse(file.read(), content_type='application/pdf')
                response['Content-Disposition'] = f'attachment; filename="{pdf_path}"'
                return response

    #response = HttpResponse(content_type='application/pdf')
    #response['Content-Disposition'] = f'attachment; filename="{pdf_path}"'
    #response = create_single_pdf(run.result_data.data['pages'], response)
    #return response


def health_check(request):
    return JsonResponse({"status": "up"})


urlpatterns = [
    re_path(r'^$', lambda _: redirect('/main')),
    path('', include('social_django.urls', namespace='social')),
    path('admin/', admin.site.urls),
    path('main/', decorator_include(login_required, ('main.urls', "main"),
                                    namespace="main")),
    path('health', health_check),
    path('search', search_files),
    path('<str:id>/result.pdf', download_pdf),
    path("<str:id>/result.json", download_json),
    url(r'^logout/$', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
]

generic-ner-ui/generic-ner-ui/main/urls.py
from django.urls import path

from . import views

"""Register urls here
"""

urlpatterns = [
    path("", views.base_page, name="base"),
    path("upload", views.upload, name="upload"),
    path("admin", views.admin_page, name="admin"),
    path("view/<str:id>", views.details, name="details"),
    path("delete_paths", views.delete_files, name="delete_files"),
    path("delete_tiffs", views.delete_tiffs, name="delete_tiffs"),
    path("rename_group", views.rename_group, name="rename_group"),
    path("delete/<str:id>", views.delete, name="delete"),
    path("view/<str:id>/<str:view>", views.details, name="details"),
    path("img/<str:id>/<int:page>.png", views.image, name="image"),
    path("ocr_data.zip", views.download_all, name="download_data"),
    path("<str:id>/result.pdf", views.download_pdf, name="download_pdf"),
    path("<str:id>/result.txt", views.download_txt, name="download_txt"),
    path("<str:id>/result.json", views.download_json, name="download_json"),
    path("<str:id>/original", views.download_original, name="download_original"),
    path("uploads", views.upload_view, name="upload_view"),
    path("updates", views.check_status_updates, name="check_status_updates"),
    path("corrections", views.update_human_corrections, name="update_human_corrections"),
    path("update_marked_complete", views.update_marked_complete, name="update_marked_complete"),
]

generic-ner-ui/generic-ner-ui/templates/admin.html
{% load save_static %}
<html lang="en">
<head>
    <title>BOW - Batch OCR Webservice</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% save_static 'img/favicon.ico' %}"/>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load bootstrap4 %}

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
          crossorigin="anonymous"
    >

    {% bootstrap_javascript jquery="True" %}
    {% bootstrap_css %}
    <link href="{% save_static 'css/style.css' %}" type="text/css" rel="stylesheet"/>
</head>
<body>
{% include "global/header.html" with upload="True" %}
{% load icons %}
{% load save_static %}
{% load tz %}

{% localtime on %}

<div class="container">
    <h3 style="margin-bottom: 30px; margin-top: 30px;">Admin Console</h3>    
</div>
<div class="container">
    <h4 style="margin-bottom: 30px; margin-top: 30px;">Errors</h4>
    <table class="table">
        <tr>
            <th scope="col">Task-Id</th>
            <th scope="col">User</th>
            <th scope="col">File</th>
            <th scope="col">Uploaded</th>
            <th scope="col">Lang.</th>
            <th scope="col">Error</th>
            <th scope="col"></th>
        </tr>
        {% for run in error_runs %}
        <tr style="font-size: 14px;">
            <td scope="row">{{ run.task_id }}</td>
            <td scope="row">{{ run.user_id }}</td>
            <td scope="row">{{ run.file_name }}</td>
            <td scope="row" style="width: 100px;">{{ run.upload_date|date:'Y-m-d' }}</td>
            <td scope="row" style="width: 50px;">{{ run.lang }}</td>
            <td scope="row" style="width: 100px;" id="status-col-{{run.task_id}}">
                {{ run.error }}
            </td>
            <td scope="row" style="width: 100px;text-align: right;">
                <a href="{% url 'main:download_original' id=run.task_id %}" download="{{ run.file_name }}"style="padding: 5px;color: #075071;margin-left:10px">
                    <i class="fa fa-download"></i> Original File
                </a>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
<div class="container">
    <h4 style="margin-bottom: 30px; margin-top: 30px;">User Stats</h4>
    <table class="table">
        <tr>
            <th scope="col">User</th>
            <th scope="col">Files</th>
            <th scope="col">Errors</th>
            <th scope="col">Pages</th>
            <th scope="col">Queued</th>
            <th scope="col">Processing</th>
            <th scope="col">Storage</th>
        </tr>
        {% for user,stats in user_stats.items %}
        <tr>
            <td scope="row">{{ user }}</td>
            <td scope="row">{{ stats.1 }}</td>
            <td scope="row">{{ stats.0 }}</td>
            <td scope="row">{{ stats.2 }}</td>
            <td scope="row">{{ stats.3 }}</td>
            <td scope="row">{{ stats.4 }}</td>
            <td scope="row">{{ stats.5 }}</td>
        </tr>
        {% endfor %}
    </table>
</div>


<div class="container">
    <h4 style="margin-bottom: 30px; margin-top: 30px;">Review Stats</h4>
    <table class="table">
        <tr>
            <th scope="col">File</th>
            <td class="table_line"></td>

            <th scope="col">Text Length</th>
            <td class="table_line"></td>

            <th scope="col">Operations</th>
            <th scope="col"></th>
            <th scope="col"></th>

            <td class="table_line"></td>
            <th scope="col">Guided Review</th>
            <th scope="col"></th>

            <td class="table_line"></td>
            <th scope="col">Human Corrections</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
        
        <tr>
            <th scope="col"></th>
            <td class="table_line"></td>

            <th scope="col"></th>
            <td class="table_line"></td>

            <th scope="col">add</th>
            <th scope="col">remove</th>
            <th scope="col">update</th>

            <td class="table_line"></td>
            <th scope="col">open</th>
            <th scope="col">reviewed</th>
            
            <td class="table_line"></td>    
            <th scope="col">manual</th>
            <th scope="col">suggestion</th>
            <th scope="col">is_ok</th>
            <th scope="col">remove</th>
        </tr>

        {% for key, values in correction_stats.items %}
        <tr >
            <td scope="row">{{ key }}</td>
            <td class="table_line"></td>
            <td class="floatme-right" scope="row">{{ values.text_len|default_if_none:"--" }}</td>

            <td class="table_line"></td>
            <td class="floatme-right" scope="row">{{ values.operation_add|default_if_none:"--" }}</td>
            <td class="floatme-right table_line" scope="row">{{ values.operation_remove|default_if_none:"--" }}</td>
            <td class="floatme-right table_line" scope="row">{{ values.operation_update|default_if_none:"--" }}</td>

            <td class="table_line"></td>
            <td class="floatme-right" scope="row">{{ values.corrections_left|default_if_none:"--" }}</td>
            <td class="floatme-right table_line" scope="row">{{ values.corrections_reviewed|default_if_none:"--" }}</td>
            
            <td class="table_line"></td>
            <td class="floatme-right" scope="row">{{ values.c_correction_manual | default_if_none:"--" }}%</td>
            <td class="floatme-right" scope="row">{{ values.c_correction_accept_suggestion | default_if_none:"--" }}%</td>
            <td class="floatme-right" scope="row">{{ values.c_correction_is_ok | default_if_none:"--" }}%</td>
            <td class="floatme-right" scope="row">{{ values.c_correction_removed | default_if_none:"--" }}%</td> <!--|add:"%"-->
        </tr>                
        {% endfor %}

        <!-- summative metrics -->
        <tr>
            <th scope="col">Sum</th>
            <td class="table_line"></td>
            <th class="floatme-right" scope="col">{{ correction_stats_sum.text_len }}</th>
            <td class="table_line"></td>
            <th class="floatme-right" scope="col">{{ correction_stats_sum.operation_add }}</th>
            <th class="floatme-right" scope="col">{{ correction_stats_sum.operation_remove }}</th>
            <th class="floatme-right" scope="col">{{ correction_stats_sum.operation_update }}</th>
            <td class="table_line"></td>
            <th class="floatme-right" scope="col">{{ correction_stats_sum.corrections_left }}</th>
            <th class="floatme-right" scope="col">{{ correction_stats_sum.corrections_reviewed }}</th>            
            <td class="table_line"></td>    
            <th class="floatme-right" scope="col"></th>
            <th class="floatme-right" scope="col"></th>
            <th class="floatme-right" scope="col"></th>
            <th class="floatme-right" scope="col"></th>
        </tr>
        <tr>
            <th scope="col">Mean</th>
            <td class="table_line"></td>
            <th class="floatme-right" scope="col">{{ correction_stats_mean.text_len }}</th>
            <td class="table_line"></td>
            <th class="floatme-right" scope="col">{{ correction_stats_mean.operation_add }}</th>
            <th class="floatme-right" scope="col">{{ correction_stats_mean.operation_remove }}</th>
            <th class="floatme-right" scope="col">{{ correction_stats_mean.operation_update }}</th>
            <td class="table_line"></td>
            <th class="floatme-right" scope="col"></th>
            <th class="floatme-right" scope="col"></th>
            <td class="table_line"></td>    
            <th class="floatme-right" scope="col">{{ correction_stats_mean.c_correction_manual }}%</th>
            <th class="floatme-right" scope="col">{{ correction_stats_mean.c_correction_accept_suggestion }}%</th>
            <th class="floatme-right" scope="col">{{ correction_stats_mean.c_correction_is_ok }}%</th>
            <th class="floatme-right" scope="col">{{ correction_stats_mean.c_correction_removed }}%</th>
        </tr>

    </table>
</div>


{% endlocaltime %}
</body>
</html>

generic-ner-ui/generic-ner-ui/templates/base.html
{% load save_static %}
<html lang="en">
<head>
    <title>BOW - Batch OCR Webservice</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% save_static 'img/favicon.ico' %}"/>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load bootstrap4 %}

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
          crossorigin="anonymous"
    >

    {% bootstrap_javascript jquery="True" %}
    {% bootstrap_css %}
    <link href="{% save_static 'css/style.css' %}" type="text/css" rel="stylesheet"/>
</head>
<body>
{% include "global/header.html" with upload="True" %}
{% include "main-page/pipeline-status.html" %}
</body>
</html>

generic-ner-ui/generic-ner-ui/templates/upload.html
{% load save_static %}
{% load icons %}
<html lang="en">

<head>
    <title>BOW - Batch OCR Webservice</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% save_static 'img/favicon.ico' %}"/>

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load bootstrap4 %}

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    {% bootstrap_javascript jquery="True" %}
    {% bootstrap_css %}
    <link href="{% save_static 'css/style.css' %}" type="text/css" rel="stylesheet" />
</head>

<body>
    {% include "global/header.html" %}
    <div class="container">
        {% include "global/back.html" %}
    </div>
    <div class="container" id="upload-info">
        <h3 style="margin-bottom: 30px; margin-top: 0px;">Upload New Files</h3>

        <h5>Metadata</h5>
        <small class="form-text text-muted" style="margin-bottom: 20px;">Select the document language and fill in the group name before
            uploading files.<br>
            Once you select files the upload starts automatically.</small>
        <div class="form-group row">
            <label class="col-sm-3" for="custom-language-select">Document Language</label>
            <div class="col-sm-4">
                <select class="form-select" id="custom-language-select" onchange="activateUpload();">
                    <option disabled selected value="NONE"> - select language - </option>
                    <option value="eng">English</option>
                    <option value="deu">German</option>
                    <option value="deu_fraktur">German (Fraktur)</option>
                    <option value="fra">French</option>
                    <option value="rus">Russian</option>
                </select>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3" for="bucket">Group Name</label>
            <div class="col-sm-4">
                <span style="display: inline-block;margin: 7px;cursor: pointer;">
                {% for g in groups %}
                    <span class="badge badge-primary" onclick="$('#bucket').val('{{g}}')">{{g}}</span>
                {% endfor %}
                </span>
                <input id="bucket" class="form-control" type="text" placeholder="Unspecified">
                <small class="form-text text-muted">Use a name to group multiple files in the overview. 
                </small>
            </div>
        </div>
        <hr />
        <h5>Files</h5>
        <small class="form-text text-muted" style="margin-bottom: 20px;">To start the upload you can either upload files
            from your local computer or select files from OneDrive.<br>Allowed file types: .jpg, .png, .pdf, .arw, .dng, .tiff</small>
        <div class="row align-items-center">
            <div class="col-sm">
                <input id="file-input" class="custom-file-input" type="file" name="myFiles" multiple
                    style="display:none" accept=".png,.jpg,.jpeg,.pdf,.dng,.arw,.tif,.tiff">
                <div class="dropzone" id="drop-zone">
                    <span draggable="false" class="select-notice" style="margin-top: 30px;"><span class="inner">Drag and drop files here to
                        start uploading them<br><br> or <br><br></span>
                        <button class="btn btn-primary" disabled id="file-button">Select Files to Upload</button>
                    </span>
                    <span draggable="false" class="drop-notice" style="margin-top: 60px;">Drop Files to Upload
                        Them</span>
                </div>
            </div>
            <div class="col-sm-1 text-muted" style="text-align: center;">
                or
            </div>
            <div class="col-sm-4" style="text-align: center;">
                <button style="display: inline-block;" disabled id="upload-btn-onedrive" class="btn btn-primary" onClick="launchOneDrivePicker()"
                    data-toggle="tooltip" data-placement="top" title=""
                    data-original-title="Click here to upload files directly from OneDrive">Select Files from OneDrive
                    <i style="margin-left:5px;" class="fa fa-cloud"></i>
                </button>
            </div>
        </div>

    </div>
    <div class="container" id="upload-status" style="display: none">
        <h3 style="margin-bottom: 10px; margin-top: 30px;">Upload Progress</h3>
        <small class="form-text text-muted" style="margin-bottom: 20px;">We are currently uploading your files. Do not
            close this browser window until the upload is finished.</small>
        <div class="no-bullets" id="file-status"></div>
    </div>
    <template id="temp-progress">
        <div class="row align-items-center">
            <span class="file-name col-sm-5"></span>
            <div class="col-sm-4">
                <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: 0%;">0%</div>
                </div>
                <div class="error-msg"></div>
            </div>
        </div>
        <hr />
    </template>
    <template id="temp-onedirve">
        <div class="row align-items-center">
            <span class="file-name col-sm-5"></span>
            <div class="col-sm-4">
                <div class="msg">
                    <span>Moving from OneDrive ...</span>
                </div>
                <div class="error-msg"></div>
            </div>
        </div>
        <hr />
    </template>
</body>

</html>
<script type="text/javascript" src="https://js.live.net/v7.2/OneDrive.js"></script>
<script type="application/javascript">
    let processing = false;

    function activateUpload() {
        document.querySelector('#upload-btn-onedrive').disabled = false;
        document.querySelector('#file-button').disabled = false;
        dropArea = document.getElementById("drop-zone");
        dropArea.classList.remove("dz-disable")
    }

    function startUpload(filesData) {
        const languageSelect = document.getElementById("custom-language-select");
        const groupName = document.getElementById("bucket");
        const url = "{% url 'main:upload' %}";

        document.getElementById("back-button").style.display = "none"
        document.getElementById("upload-info").style.display = "none"
        document.getElementById("upload-status").style.display = "block"

        postSingle(filesData, url, languageSelect.value, groupName.value, undefined);
    }

    function postFiles(files) {
        const filesArray = [];
        for (const file of files) {
            filesArray.push({
                "mode": "file",
                "data": file,
                "name": file.name
            });
        }
        startUpload(filesArray);
    }

    function postOneDriveFiles(files) {
        const filesArray = [];
        for (const item of files.value) {
            filesArray.push({
                "mode": "url",
                "data": item["@microsoft.graph.downloadUrl"],
                "name": item.name
            });
        }
        startUpload(filesArray);
    }

    function postSingle(files, url, language, bucket, responseUrl) {
        processing = true;
        const file = files.shift();
        const data = new FormData();
        if (file.mode == "url") {
            data.set(file.mode, file.data);
        }
        else {
            data.set(file.mode, file.data, file.name);
        }
        data.set("name", file.name);
        data.set("language", language);
        data.set("bucket", bucket);

        console.log("start upload: " + file.name);
        if (file.mode == "file") {
            var template = document.querySelector('#temp-progress');
        }
        else {
            var template = document.querySelector('#temp-onedirve');
        }
        var clone = template.content.cloneNode(true);
        clone.querySelector(".file-name").textContent = file.name
        const statusList = document.getElementById("file-status");
        statusList.prepend(clone)
        currentProgressEl = statusList.firstElementChild



        const request = new XMLHttpRequest();
        hasError = false
        request.onreadystatechange = function () {
            if (this.readyState === 4) {
                if (this.status === 200) {
                    console.log("successfully uploaded: " + file.name);
                    if (file.mode == "file") {
                        currentProgressEl.querySelector(".progress-bar").textContent = "Done Uploading"
                        currentProgressEl.querySelector(".progress-bar").style.width = "100%"
                    } else {
                        currentProgressEl.querySelector(".msg").textContent = "Done Moving!"
                    }
                } else {
                    hasError=true
                    currentProgressEl.querySelector(".error-msg").textContent = "Error: " + this.response
                    if (file.mode == "file") {
                        currentProgressEl.querySelector(".progress-bar").style.display = "none"
                    } else {
                        currentProgressEl.querySelector(".msg").style.display = "none"
                    }
                    console.log("error uploading: " + file.name + ", error: " + this.response);
                }
                if (files.length === 0) {
                    processing = false;
                    if (!hasError) {
                        window.location = "{% url 'main:base' %}";
                    }
                } else {
                    postSingle(files, url, language, bucket, responseUrl);
                }

            }
        };
        if (file.mode == "file") {
            request.upload.onprogress = (event) => {
                // event.loaded returns how many bytes are downloaded
                // event.total returns the total number of bytes
                // event.total is only available if server sends `Content-Length` header
                console.log(`Uploaded ${event.loaded} of ${event.total} bytes`);
                currentProgressEl.querySelector(".progress-bar").textContent = Math.round(event.loaded / event.total * 100) + "%"
                currentProgressEl.querySelector(".progress-bar").style.width = Math.round(event.loaded / event.total * 100) + "%"
            }
        }
        request.open("POST", url, true);
        request.send(data);
    }

    function launchOneDrivePicker() {
        const odOptions = {
            clientId: "{{ onedrive_id }}",
            action: "download",
            multiSelect: true,
            advanced: {},
            success: postOneDriveFiles,
            cancel: function () {
                processing = false;
            },
            error: function (error) {
                const statusList = document.getElementById("upload-status");
                const statusElement = document.createElement("li");
                statusElement.innerText = "error using onedrive picker: " + error;
                console.log("error using onedrive picker: " + error);
                statusList.style.display = 'block';
                statusList.appendChild(statusElement);
                processing = false;
            }
        };
        OneDrive.open(odOptions);
        processing = true;
    }

    window.onbeforeunload = function (e) {
        if (!processing) {
            return;
        }

        const message = "Files are currently uploading, do you want to cancel?";
        e = e || window.event;
        // For IE and Firefox
        if (e) {
            e.returnValue = message;
        }

        // For Safari
        return message;
    };

    const fileSelect = document.getElementById("file-input");
    const fileElem = document.getElementById("file-button");

    fileElem.addEventListener("click", function (e) {
        fileSelect.click();
    }, false);
    fileSelect.addEventListener("change", function (e) {
        postFiles(this.files);
    }, false);

    //
    // dropzone
    //
    // ************************ Drag and drop ***************** //
    let dropArea = document.getElementById("drop-zone");

    // Prevent default drag behaviors
    ['dragenter', 'dragover', 'dragleave', 'drop'].forEach(eventName => {
        dropArea.addEventListener(eventName, preventDefaults, false);
        document.body.addEventListener(eventName, preventDefaults, false);
    });

    // Highlight drop area when item is dragged over it
    ['dragenter', 'dragover'].forEach(eventName => {
        dropArea.addEventListener(eventName, highlight, false)
    });

    ['dragleave', 'drop'].forEach(eventName => {
        dropArea.addEventListener(eventName, unhighlight, false)
    });

    // Handle dropped files
    dropArea.addEventListener('drop', handleDrop, false);

    function preventDefaults(e) {
        e.preventDefault();
        e.stopPropagation();
    }

    function highlight(e) {
        dropArea.classList.add('highlight')
    }

    function unhighlight(e) {
        dropArea.classList.remove('highlight')
    }

    function handleDrop(e) {
        var dt = e.dataTransfer;
        var files = dt.files;

        postFiles(files)
    }

    dropArea.classList.add("dz-disable")
</script>