generic-ner-ui/generic-ner-ui/generic_ner_ui/urls.py
import tempfile
from decorator_include import decorator_include
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.http import JsonResponse
from django.urls import include, path, re_path

from generic_ner_ui import settings
from generic_ner_ui.utils import redirect

import datetime
import itertools
import json
from pathlib import Path
from generic_ner_ui.models import Run
from django.db.models import Q
from django.http import HttpResponse
from main.views import create_single_pdf, download_pdf
from generic_ner_ui.settings import SECRET, ALLOWED_IPS
from loguru import logger
from main.processing import compress
from main.processing import download_minio_file

def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[-1].strip()
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def validate_access(request):
    try:
        #if get_client_ip(request) not in ALLOWED_IPS:
        #    return False
        request_secret = request.GET.getlist("secret")[0]
        if request_secret != SECRET:
            return False
        return True
    except Exception as e:
        logger.info(f"{get_client_ip(request)}, {e}")
        return False


def search_files(request):
    try:
        if not validate_access(request):
            return JsonResponse([{"access": "denied"}], safe=False)
        request_date = request.GET.getlist("lastApproved")[0]
        date = datetime.datetime.strptime(request_date, "%Y%m%dT%H%M%S%z").strftime("%Y-%m-%d %H:%M:%S.%f%z")
    except Exception as e:
        return JsonResponse([{"exception": str(e)}], safe=False)

    runs = Run.objects.filter( (Q(latest_review_date__gt=date) | Q(finish_date__gt=date)) & Q(marked_complete=True) )
    runs = list(reversed(runs))

    context = []
    for r in runs:
        if r.latest_review_date:
            date = r.latest_review_date.strftime("%Y%m%dT%H%M%S%z")
        elif r.finish_date:
            date = r.finish_date.strftime("%Y%m%dT%H%M%S%z")
        else:
            date = ""
        context.append({
            "id": r.task_id,
            "lastApproved": date,
            "title": f"{Path(r.file_name).stem}.pdf",
            "resultPdfUrl": request.build_absolute_uri(f"/bow/{r.task_id}/result.pdf?secret={SECRET}").replace("http://", "https://"),
            "jsonUrl": request.build_absolute_uri(f"/bow/{r.task_id}/result.json?secret={SECRET}").replace("http://", "https://")
        })
    return JsonResponse(context, safe=False, json_dumps_params={'ensure_ascii': False})


def download_json(request, id):
    if not validate_access(request):
        return JsonResponse([{"access": "denied"}], safe=False)

    run = Run.objects.get(task_id=id)
    data = run.result_data.data

    file_root = Path(run.file_name).stem
    filename_base = Path(data['output']).stem

    date = run.upload_date.strftime('%Y-%m-%d_%H-%M-%S')
    if run.latest_review_date:
        date = run.latest_review_date.strftime('%Y-%m-%d_%H-%M-%S')
    elif run.finish_date:
        date = run.finish_date.strftime('%Y-%m-%d_%H-%M-%S')
    filename_json = f"{filename_base}_AC-OCR-BOW_{date}.json"
    request_json_path = f"{file_root}/{filename_json}"

    response = HttpResponse(json.dumps(data, ensure_ascii=False), content_type='application/json')
    response['Content-Disposition'] = f'attachment; filename="{request_json_path}"'
    return response


def download_pdf(request, id):
    if not validate_access(request):
        return JsonResponse([{"access": "denied"}], safe=False)

    run = Run.objects.get(task_id=id)

    # PDF un-reviewed
    if not run.latest_review_date:
        ext = f"_AC-OCR-BOW-Unrev_{str(run.upload_date.strftime('%Y-%m-%d_%H-%M-%S'))}.pdf"
        pdf_path = f"{Path(run.file_name).stem}{ext}"

        minio_path = run.result_prep["output"]
        response = download_minio_file(minio_path, content_type="application/pdf")
        response['Content-Disposition'] = f'attachment; filename="{pdf_path}"'
        return response

    ext = f"_AC-OCR-BOW-Unrev_{str(run.upload_date.strftime('%Y-%m-%d_%H-%M-%S'))}.pdf"
    if run.finish_date != None:
        ext = f"_AC-OCR-BOW-Unrev_{str(run.finish_date.strftime('%Y-%m-%d_%H-%M-%S'))}.pdf"
    if run.latest_review_date != None:
        ext = f"_AC-OCR-BOW-Rev_{str(run.latest_review_date.strftime('%Y-%m-%d_%H-%M-%S'))}.pdf"

    pdf_path = f"{Path(run.file_name).stem}{ext}"

    with tempfile.NamedTemporaryFile(suffix='.pdf', delete=True) as temp_1:
        _ = create_single_pdf(run.result_data.data['pages'], temp_1.name)

        with tempfile.NamedTemporaryFile(suffix='.pdf', delete=True) as temp_2:
            success = compress(temp_1.name, temp_2.name, power=1)
            export_file = temp_1.name
            if success:
                export_file = temp_2.name

            with open(export_file, 'rb') as file:
                response = HttpResponse(file.read(), content_type='application/pdf')
                response['Content-Disposition'] = f'attachment; filename="{pdf_path}"'
                return response

    #response = HttpResponse(content_type='application/pdf')
    #response['Content-Disposition'] = f'attachment; filename="{pdf_path}"'
    #response = create_single_pdf(run.result_data.data['pages'], response)
    #return response


def health_check(request):
    return JsonResponse({"status": "up"})


urlpatterns = [
    re_path(r'^$', lambda _: redirect('/main')),
    path('', include('social_django.urls', namespace='social')),
    path('admin/', admin.site.urls),
    path('main/', decorator_include(login_required, ('main.urls', "main"),
                                    namespace="main")),
    path('health', health_check),
    path('search', search_files),
    path('<str:id>/result.pdf', download_pdf),
    path("<str:id>/result.json", download_json),
    url(r'^logout/$', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
]

generic-ner-ui/generic-ner-ui/main/urls.py
from django.urls import path

from . import views

"""Register urls here
"""

urlpatterns = [
    path("", views.base_page, name="base"),
    path("upload", views.upload, name="upload"),
    path("admin", views.admin_page, name="admin"),
    path("view/<str:id>", views.details, name="details"),
    path("delete_paths", views.delete_files, name="delete_files"),
    path("delete_tiffs", views.delete_tiffs, name="delete_tiffs"),
    path("rename_group", views.rename_group, name="rename_group"),
    path("delete/<str:id>", views.delete, name="delete"),
    path("view/<str:id>/<str:view>", views.details, name="details"),
    path("img/<str:id>/<int:page>.png", views.image, name="image"),
    path("ocr_data.zip", views.download_all, name="download_data"),
    path("<str:id>/result.pdf", views.download_pdf, name="download_pdf"),
    path("<str:id>/result.txt", views.download_txt, name="download_txt"),
    path("<str:id>/result.json", views.download_json, name="download_json"),
    path("<str:id>/original", views.download_original, name="download_original"),
    path("uploads", views.upload_view, name="upload_view"),
    path("updates", views.check_status_updates, name="check_status_updates"),
    path("corrections", views.update_human_corrections, name="update_human_corrections"),
    path("update_marked_complete", views.update_marked_complete, name="update_marked_complete"),
]

generic-ner-ui/generic-ner-ui/templates/display/document-view.html
<div class="col position-col img-holder">
    <img src="{% url 'main:image' id=task_id page=forloop.counter0 %}" width="100%"
         style="display: block"/>
    {% if view == "ocr" %}
    {% for entry in page.ner.entries %}
    {% if entry.method != "remove" %}
    <span id="img-hover-{{p_number}}-{{forloop.counter0}}" class="doc-overlay" style="left:{{ entry.left_norm }}%;top:{{ entry.top_norm }}%;width:{{ entry.width_norm }}%;height:{{ entry.height_norm }}%;"></span>
    {% endif %}
    {% endfor %}
    {% endif %}
</div>

generic-ner-ui/generic-ner-ui/templates/display/entity-view.html
<div class="col">
    <ul class="list-group">
        {% for group in page.ner.entity_groups %}
        <li class="list-group-item">
            {% if group.name %}
            <h3 class="list-group-item-heading">{{ group.name }}</h3>
            {% endif %}
            {% for entity in group.entities %}
            <p class="list-group-item">{{ entity.type }}: {{ entity.value }}</p>
            {% endfor %}
        </li>
        {% endfor %}
    </ul>
</div>

generic-ner-ui/generic-ner-ui/templates/display/ner-stats.html
<table class="table">
    <tr>
        <th scope="col">Entity text</th>
        <th scope="col">Entity type</th>
        <th scope="col">Count</th>
        <th scope="col">Pages</th>
    </tr>
    {% for entitystat in entitystats %}
    <tr>
        <td scope="row">{{ entitystat.text }}</td>
        <td scope="row">{{ entitystat.type }}</td>
        <td scope="row">{{ entitystat.count }}</td>
        <td scope="row">{{ entitystat.pages }}</td>
    </tr>
    {% endfor %}
</table>

generic-ner-ui/generic-ner-ui/templates/display/ocr-view.html
<div class="col ocr-holder">
    <svg width="100%" style="height:inherit" viewBox="0 0 {{ page.preprocessing.width }} {{ page.preprocessing.height }}"></svg>
    {% for entry in page.ner.entries %}
    
    {% if entry.method != "remove" %}
        <!-- OCR text holder -->
        <div class="outer-text-holder" style="left:{{ entry.left_norm }}%;
                                                top:{{ entry.top_norm }}%;
                                                width:{{ entry.width_norm }}%;
                                                height:{{ entry.height_norm }}%;">
        {% if entry.method == "update" or entry.method == "add" %}
            <span spellcheck="false" contenteditable value="#img-hover-{{p_number}}-{{forloop.counter0}}" onmouseover="$('#img-hover-{{p_number}}-{{forloop.counter0}}').addClass('active')" onmouseout="$('#img-hover-{{p_number}}-{{forloop.counter0}}').removeClass('active')" class="inner-text-holder underline-wavy-green">{{ entry.human_correction }}</span>
        {% else %}
            <span spellcheck="false" contenteditable value="#img-hover-{{p_number}}-{{forloop.counter0}}" onmouseover="$('#img-hover-{{p_number}}-{{forloop.counter0}}').addClass('active')" onmouseout="$('#img-hover-{{p_number}}-{{forloop.counter0}}').removeClass('active')" class="inner-text-holder {% if entry.correction|length > 0 %} underline-wavy-red{% elif entry.conf < 60 %} underline-wavy-blue{% endif %}">{{ entry.text }}</span>
        {% endif %}

        <!-- correction hover tooptip -->
        {% if entry.method != "update" and entry.method != "add" and entry.correction|length > 0 %} 
            <div class="correction-tooltip">
                {% for c in entry.correction %}
                    <span class="corr-entry" onclick="select_correction(this)">{{ c }}</span>
                {% endfor %}
                <hr>
                <div class="flex">
                    <input value="{{ entry.text }}">
                    <span class="toolbar-btn" onclick="custom_correction(this)" id="contract-btn">
                        <i class="fa fa-check"></i>
                    </span>
                </div>
                <hr>
                <span class="corr-entry" style="float: left; width: 50%;" onclick="skip_correction(this)">
                    <i class="fa fa-arrow-right" aria-hidden="true"></i> Is Ok
                </span>
                <span class="corr-entry" style="float: right; width: 50%" onclick="remove_correction(this)">
                    <i class="fa fa-ban" aria-hidden="true"></i> Remove
                </span>
            </div>
        {% elif entry.conf < 60 and not entry.human_correction  %}
            <div class="correction-tooltip-alt" style="float:left;">
                <div class="flex">
                    <input value="{{ entry.text }}">
                    <span class="toolbar-btn" onclick="custom_correction(this)" id="contract-btn">
                        <i class="fa fa-check"></i>
                    </span>
                </div>
                <hr>
                <span class="corr-entry" style="display:inline;" onclick="skip_correction(this)">
                    <i class="fa fa-arrow-right" aria-hidden="true"></i> Is Ok
                </span>
                <span class="corr-entry" style="display:inline;" onclick="remove_correction(this)">
                    <i class="fa fa-ban" aria-hidden="true"></i> Remove
                </span>
            </div>
        {% else %}
            <div class="correction-tooltip-alt">
                <div class="flex">
                    <input value="{% if entry.method == "update" or entry.method == "add" %}{{ entry.human_correction }}{% else %}{{ entry.text }}{% endif %}">
                    <span class="toolbar-btn" onclick="custom_correction(this)" id="contract-btn">
                        <i class="fa fa-check"></i>
                    </span>
                </div>
                <hr>
                <span class="corr-entry" onclick="remove_correction(this)"><i class="fa fa-ban" aria-hidden="true"></i> Remove</span>
            </div>
        {% endif %}
        </div>
    {% endif %}
    {% endfor %}
</div>

generic-ner-ui/generic-ner-ui/templates/display/text-view.html
<div class="col">
    
    <span>
        {% for entry3 in page.ner.entries %}

            <!-- dont show removed boxes -->
            {% if entry3.method != "remove" %}

                <!-- show normal ocr text if no human correction exists -->
                {% if entry3.correction|length == 0 and not entry3.human_correction %}
                    {{ entry3.text }}
                {% elif entry3.human_correction %}
                    <span class="underline-wavy-green plain-holder">{{ entry3.human_correction }}</span>
                {% else %}
                    <span class="underline-wavy-red plain-holder">{{ entry3.text }}
                        <!-- <div class="correction-tooltip">{% for c in entry3.correction %}<span class="corr-entry">{{ c }}</span>{% endfor %}</div> -->
                    </span>
                {% endif %}
            {% endif %}
            
        {% endfor %}
    </span>

    <hr>
    <!-- show human added rows -->
    <span>
        {% for entry3 in page.ner.entries %}
            {% if entry3.method != "remove" %}
                {% if entry3.human_add %}
                    {{ entry3.human_correction }}
                {% endif %}
            {% endif %}
        {% endfor %}
    </span>   
</div>